# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='buzz',
        ),
    ]
